### ISSUE TITLE
satis:build on clean install fails

### ISSUE THREAD

**Issue by LVoogd** [terramar-labs/packages#122]
I downloaded the latest release (v3.2.0) today and followed the guide (I also tried this with the latest code, this yielded the same error). I used the provided docker-compose. Running the following command yields an error:

```bash
root@4ba9e9dca2eb:/app# php bin/console -vvv satis:build
{
    "name": "Terramar Labs",
    "homepage": "https:\/\/github.com\/terramar-labs\/packages",
    "output-dir": "\/app\/satis",
    "repositories": [],
    "output-html": false,
    "require-dependencies": true,
    "require-dev-dependencies": true,
    "config": {
        "gitlab-domains": []
    },
    "archive": {
        "directory": "dist",
        "format": "tar",
        "prefix-url": "https:\/\/localhost",
        "skip-dev": true
    }
}
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/app): git branch --no-color --no-abbrev -v
Executing command (/app): git describe --exact-match --tags
Executing command (/app): git log --pretty="%H" -n1 HEAD
Executing command (/app): hg branch
Executing command (/app): fossil branch list
Executing command (/app): fossil tag list
Executing command (/app): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /app/vendor/composer/installed.json

                                                                                                                                                                              
  [UnexpectedValueException]                                                                                                                                                  
  Unknown package has no name defined ([{"name":"chrisboulton\/php-resque","version":"dev-master","version_normalized":"dev-master","source":{"type":"git","url":"https:\/\/  
  github.com\/chrisboulton\/php-resque.git","reference":"968b7e6a307a2079051dfc571d2fc2be0546209f"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/chrisboulto  
  n\/php-resque\/zipball\/968b7e6a307a2079051dfc571d2fc2be0546209f".....}])

Exception trace:
 () at /app/vendor/composer/composer/src/Composer/Package/Loader/ArrayLoader.php:44
 Composer\Package\Loader\ArrayLoader->load() at /app/vendor/composer/composer/src/Composer/Repository/FilesystemRepository.php:63
 Composer\Repository\FilesystemRepository->initialize() at /app/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at /app/vendor/composer/composer/src/Composer/Plugin/PluginManager.php:256
 Composer\Plugin\PluginManager->loadRepository() at /app/vendor/composer/composer/src/Composer/Plugin/PluginManager.php:76
 Composer\Plugin\PluginManager->loadInstalledPlugins() at /app/vendor/composer/composer/src/Composer/Factory.php:377
 Composer\Factory->createComposer() at /app/vendor/composer/composer/src/Composer/Factory.php:569
 Composer\Factory::create() at /app/src/Console/Application.php:141
 Terramar\Packages\Console\Application->getComposer() at /app/vendor/composer/satis/src/Console/Command/BuildCommand.php:174
 Composer\Satis\Console\Command\BuildCommand->execute() at /app/src/Plugin/Satis/Command/BuildCommand.php:72
 Terramar\Packages\Plugin\Satis\Command\BuildCommand->execute() at /app/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:873
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:202
 Symfony\Component\Console\Application->doRun() at /app/src/Console/Application.php:62
 Terramar\Packages\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /app/bin/console:12

satis:build [--repository-url [REPOSITORY-URL]] [--no-html-output] [--skip-errors] [--stats] [--] [<file>] [<output-dir>] [<packages>]...

```
 As seen above something doesn't seem to line up in the composer packages. Maybe a version mismatch between 'composer/satis' and 'composer/composer'?

**Comment by LVoogd** [comment]
If someone could provide me with a compser.lock of a working instance (with version v3.2.0) I could confirm my guess

**Comment by tiraoui** [comment]
@LVoogd I have installed this about 2 yrs ago and it worked just fine. I have also installed it today and its working as well.
One thing you have to keep in mind is that it has not been maintained in a while.

1- First error: Failed to initialize global composer: Composer could ... is basically just telling you that you dont have the config file under your user directory which belongs to composer to read the composer initialization etc for this user you are running.. Most likely or maybe you have installed composer with a different user than the one you are executing the code with.

2- The 2nd error:
  [UnexpectedValueException]                                                                                                                                                  
  Unknown package has no name defined
Most likely is that you have newer vender packages than the one came with the composer.lock
One way to test that (in case you somehow ran composer install without the lock) is to copy the lock from the git repo here into your lock in your root directory - remove the vendor directory then run: composer update.. this should bring back all correct names etc.

you can see a photo attached of my running one which i have just installed and its working..
![image](https://user-images.githubusercontent.com/43049386/103849088-2923c200-50a4-11eb-9abd-0b6d157bf666.png)

best of luck

**Comment by LVoogd** [comment]
Thanks for the response, seeing that it works on your end made me dig deeper into this problem.

The docker image/composer version seems to be the problem. The docker image used in this project defaults to the latest composer version, 2. This breaks the project. So make sure you use composer version 1!

To fix this in the docker container the following can be executed (or use `composer1 install`):
```bash
ln -f /usr/local/bin/composer1 /usr/local/bin/composer
````
I don't know if this means that it is not possible to host composer 2 packages, since all my packages are still composer 1 compatible.

**Comment by tiraoui** [comment]
You are welcome :)

Yes, logically it makes sense... If the library stays unmaintained then you will have to decide in the future what to do with it ... like it or not there will be future dependencies which will require that you update your composer...
