### ISSUE TITLE
Create view with Satis-like list of enabled packages

### ISSUE THREAD

**Issue by Wirone** [terramar-labs/packages#14]
I think it would be good to have open, Satis-like (conceptually, not visually) view with list of available (enabled) packages. It could be available on `domain.tld/packages`, and it should contain data related to `packages.json`, but presented in user-friendly way. It should be generated automatically with `packages.json`.

**Comment by tyler-sommer** [comment]
:+1: I think this is a great idea.

**Comment by markushausammann** [comment]
+1 absolutely, as it is I don't even know how to install the packages I enabled with the manager.

**Comment by bdandoy** [comment]
+1

**Comment by tyler-sommer** [comment]
Finally, an update! I recently opened a PR #55 that contains some initial improvements to the landing page. I think the app as a whole could use some touching up, and this fits right in with that.

I'm open to any suggestions on what folks want to see. I think using what Satis generates as a base is a good starting point. I also think the page should be configurable-- at least the ability to enable or disable it. Would it also make sense to have a setting that requires the user be logged in versus not?

**Comment by bernhardberger** [comment]
I just tried out your pull request locall and it looks very promising.

One thing though: as Packages is mainly aimed (at least seems like it) to be a private composer repo, I'd like to see that output behind the login screen as well.

I know, the packages.json is publicly available, but imho we should try to hide as much as possible behind the login.

**Comment by tyler-sommer** [comment]
Fixed in #64
