### ISSUE TITLE
Stop resque worker undefined function

### ISSUE THREAD

**Issue by thejahweh** [terramar-labs/packages#16]
Hi I have some trouble with Packages, because it does not update Satis if its triggered by a push or manually by GitLab. It updates only if its triggered in the console.

So I just tried to stop the worker and this is what I get:
```
[root@x composer]# bin/console resque:worker:stop -a
Stopping x.x.ch:10937:*...
PHP Fatal error:  Call to undefined function Terramar\Packages\Console\Command\Worker\posix_kill() in /var/www/x/src/Console/Command/Worker/StopCommand.php on line 61

Fatal error: Call to undefined function Terramar\Packages\Console\Command\Worker\posix_kill() in /var/www/x/src/Console/Command/Worker/StopCommand.php on line 61
```

**Comment by tyler-sommer** [comment]
Thanks for the bug report. Packages actually requires that the POSIX extension be enabled to function properly. See the [POSIX manual page](http://php.net/posix) for more information.

I will update Packages' composer.json and documentation to include this requirement.

**Comment by thejahweh** [comment]
Thanks, now it works :tada:

**Comment by tyler-sommer** [comment]
Glad to hear it!
