### ISSUE TITLE
Enable private repos

### ISSUE THREAD

**Issue by aimfeld** [terramar-labs/packages#18]
I can't get access to my private Github repos, even when I allow all options in the personal access token. After syncing, I see only my public repos, but no private ones.

**Comment by tyler-sommer** [comment]
@aimfeld Thanks for the bug report.

I've opened a PR that contains a fix (See #20) but I am not all the way set on merging it. Let me think about this issue a little more before I merge the fix. Feel free to provide input on which way my decision should go as well :)

**Comment by tyler-sommer** [comment]
The fix is merged. I'll tag a release on the 3.0.x line with the fix today.

**Comment by tyler-sommer** [comment]
I've just tagged 3.0.4 which contains this fix. See here: https://github.com/terramar-labs/packages/releases/tag/3.0.4
