### ISSUE TITLE
Missing parts in the doc

### ISSUE THREAD

**Issue by markushausammann** [terramar-labs/packages#22]
Hi, I'm missing some information in the docs.
- What does "Clone this project locally after each code push" mean?
- If I enable the Composer Satis plugin, how do I install the package?
- Where can I access the satis packages page which shows the installable versions, etc.?

And one which I was able to figure out so far:
- Why don't my changes to the twig file show? (hint: delete twig cache in /path...)

Cheers
Markus

**Comment by tyler-sommer** [comment]
Thanks for this, @markushausammann. I'll spend some time updating the documentation in the next few days.

**Comment by tyler-sommer** [comment]
Fixed in 294f0f4
