### ISSUE TITLE
Worker restart after web server restart

### ISSUE THREAD

**Issue by markushausammann** [terramar-labs/packages#23]
Am I understanding this right that the worker has to manually be restarted after every web server restart? Is there a good way to automatize this?

**Comment by markushausammann** [comment]
Actually, I just realized I don't understand why the worker even needs to run. Shouldn't the webhook be enough to make sure satis build is run?

**Comment by tyler-sommer** [comment]
Depending on your OS, you can write a startup script using init.d or launchctl or the like. [This looks like a fairly in-depth guide to writing an init.d script](https://gist.github.com/naholyr/4275302).

Per your second question, building your packages.json can take some time, so I opted to move all work on webhook receipt to a background job using resque. This way, we can allow heavy background tasks, such as those in 3.1.0 to clone the package repository and then generate Sami documentation using the local copy of the code. Further, imagine continuous integration tasks: running your code's test suite or automatically deploying to production.

**Comment by markushausammann** [comment]
Thank you very much for the explanations!
