### ISSUE TITLE
Webhook rebuilds everything instead of just the repo you want it to.

### ISSUE THREAD

**Issue by rickmills** [terramar-labs/packages#25]
Is there any reason why the web hooks cause php bin/console satis:update --build to be run on its own?

Surely it should be running a command to just tell satis to rebuild that individual repository.

As it stands packages ends up being unusable when you've got a lot of repos as it means it's forever performing a full rebuild.

**Comment by tyler-sommer** [comment]
Back when this was implemented, Satis didn't support incremental updates. It looks like it does now, though, so this should definitely be implemented.

(Very, very, very belated) Thanks!

**Comment by Aeolun** [comment]
@tyler-sommer I've added this in my fork. Essentially just adding an extra parameter in the rebuild command.

**Comment by tyler-sommer** [comment]
Thanks very much to @Aeolun this is now done! Fixed in #62
