### ISSUE TITLE
Accept input from Gitlab Web Hooks

### ISSUE THREAD

**Issue by Barbarrosa** [terramar-labs/packages#27]
Gitlab allows the creation of project web hooks to trigger external events when an event occurs, including "push events" and "tag push events". Please implement configurable support for these web hooks so I can (almost) immediately see Gitlab updates in Packages.

Please see this page for documentation: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md

**Comment by bdandoy** [comment]
This was added in 3.0.4

**Comment by Barbarrosa** [comment]
Thanks, @bdandoy.
