### ISSUE TITLE
Enhancement -- GitLab Remote URL expects root URL not remote repository

### ISSUE THREAD

**Issue by trip-somers** [terramar-labs/packages#29]
The language in the Packages Dashboard for adding remotes does not clearly indicate that the remote URL should be the root of the GitLab installation rather than a remote git repository -- which is generally called a "remote" when using git, hence my confusion.

The result of my confusion is that I added a URL that looked like this: http://gitlab.mydomain.com/web-developers/cms.git (not intended to be an actual link)

This returned non-descript HTTP 500 error responses when attempting to Sync, and I had to dig through vendor packages to find out what it was trying to do. When I saw the "/api/packages..." string appended to the end of my URL, I knew how to fix it. In retrospect, this is obvious, but "remote" is what threw me.

Documentation is not strictly clear, but this blog post hints that the root URL is expected: https://tylersommer.com/managing-private-composer-repositories-with-packages

My suggestion is that some kind of detection/validation be done on GitLab URLs when the form is processed to make sure that the URL does not point to a .git repository.

**Comment by tyler-sommer** [comment]
:+1: I don't want to rename Remotes this late in the game, but the documentation should definitely be improved. Input validation would also be fantastic, I'll keep these in mind.

Thanks for opening this. Cheers!

**Comment by tyler-sommer** [comment]
I made some improvements on this front in 9c54551ae48cbafd58f49ca58deeaa4f026eebcd which will be released in 3.2.0.

I'm still going to work on improving the documentation further, but I'm going to close this issue. If you have any more questions or suggestions, please open another ticket.

Thanks again!
