### ISSUE TITLE
Enhancement - Gitlab Group filtering

### ISSUE THREAD

**Issue by michellaurent** [terramar-labs/packages#30]
It would be nice if we can filter package by Gitlab groups.

Maybe you can add an optional "group" field in Gitlab config ...

**Comment by tyler-sommer** [comment]
:+1: Having several hundred packages and slowwwww datatables is really annoying.

**Comment by bernhardberger** [comment]
are you guys talking about the sync/import or the resulting view?

Couldn't the first one easily be solved by using a dummy user in GitLab with permissions to only those groups you want to import?

Haven't tried it myself but having the same "issue". Picked up Packages again today (looked dead last year) after seeing activity again - and meanwhile our self hosted gitlab instance has grown to hold 500+ repos where 50+ shouldn't be synced at all (not composer/php related) and around 350 more shouldn't be shown/synced too as they're project roots.

So we basocally would want 3 things:
- only sync libs/plugins/extensions with a valid composer.json
- filter those imported packages by group in the list view
- have enabled and disabled views split up for a clearer view.

I may chip in with some pull requests when time allows it after seeing activity here again ;-)
