### ISSUE TITLE
Enable possibility to add AUTH to redis

### ISSUE THREAD

**Issue by markushausammann** [terramar-labs/packages#32]
Hi

We want to run redis with a password. There doesn't seem to be a way to use the rescue workers with AUTH. How about giving the option in the config to set a password?

**Comment by tyler-sommer** [comment]
This is an excellent suggestion, thanks for submitting it!

I likely won't be able to look into this for you, but it should be doable. It may require some modifications to the `php-resque` library though.

I'll leave this ticket open in case someone wants to pick it up!

**Comment by markushausammann** [comment]
Hi, just letting you know we're not using the package anymore.

**Comment by tyler-sommer** [comment]
Turns out this was really just a documentation change. You can specify a password for redis by using a host like `redis://na:password@redis-host`. The username portion (the `na` in the previous example) of the URL is unused and can be anything.
