### ISSUE TITLE
Satis Update and Build job not including dist in output

### ISSUE THREAD

**Issue by bdandoy** [terramar-labs/packages#36]
When I run bin/console satis:update --build in the repo I get the this in the output which I expect
`"dist": {
                    "type": "zip",
                    "url": "https://gitlab.url.com/api/v3/projects/namespace%2Frepo/repository/archive.zip?sha=hash",
                    "reference": "hash",
                    "shasum": ""
                },`

When it is triggered by the webhook in gitlab that section is always missing but everything else is the same.

**Comment by tyler-sommer** [comment]
Hey @bdandoy, I know I'm probably way too late, sorry for the silence! Are you still seeing this? I didn't think Packages generated the dist information, but I can see that being desirable.

Let me know if you have any thoughts on this. Thanks for your time!

**Comment by tyler-sommer** [comment]
This was given a proper going-over in #61. Thanks again!
