### ISSUE TITLE
background tasks not run

### ISSUE THREAD

**Issue by phiamo** [terramar-labs/packages#39]
hey folks,
thanks a lot for this awesome project.

I realized that our setup does not do any background jobs. worker is running redis is setup. but since  I am quite new to redis and resque i dont know howto debug.

Do you have any tips to find out why i have to call bin/console satis:build manually to get a new packages.json generated?

thanks 
- Phil

**Comment by mikspark** [comment]
Same problem
```
[notice] Starting work on (Job{default} | ID: 9841f0002c371ba97cd171ef1d2a3075 | Terramar\Packages\Plugin\Satis\UpdateAndBuildJob | [null])
Could not open input file: bin/console
```

**Comment by mediaessenz** [comment]
Same her

**Comment by wuethrich44** [comment]
When I run `QUEUE='*' bin/resque` my jobs get processed but I wasn't able to start this command in a systemd init script 😕

**Comment by tyler-sommer** [comment]
Hi folks, sorry for the long silence.

I think the problems you're seeing in your init scripts are due to relative paths used by the application. I think that changing directories to the Packages installation root in your init script should do the trick.

Thanks for raising the issue!

**Comment by tyler-sommer** [comment]
I'm going to close this issue since it's been inactive (other than me) for some time. Please feel free to open a new ticket if you have any more problems. Thanks!
