### ISSUE TITLE
fatal: I don't handle protocol '[git@https'  

### ISSUE THREAD

**Issue by matrixbegins** [terramar-labs/packages#42]
HI I am using the packages with GITLAB. Its working great for us. Except there is a small glitch. 
When I do 
`bin/console satis:update --build` I am getting an error.

```
[RuntimeException]                                                                                                                                                                
  Failed to execute git clone --mirror '[git@https://gitlab.myreposerver.com]:company/limited-testing.git' '/root/.cache/composer/vcs/-git-https---gitlab.myreposerver.com--admin-limited-test  
  ing.git/'                                                                                                                                                                         
  Cloning into bare repository '/root/.cache/composer/vcs/-git-https---gitlab.myreposerver.com--admin-limited-testing.git'...                                                            
  fatal: I don't handle protocol '[git@https'  
```

Now I understand the URL: `[git@https://gitlab.myreposerver.com]:company/limited-testing.git` is not a valid URL. I tried in changing that in gitlab but the `square brackets []` are coming anyways.

Can you help how I can solve this problem ? Many thanks

**Comment by tyler-sommer** [comment]
This issue should be ironed out. Take a look if you have a chance, and let me know if you have any problems.

Thanks!
