### ISSUE TITLE
[Question] Is there support for controlling access to satis?

### ISSUE THREAD

**Issue by bkuhl** [terramar-labs/packages#43]
Does this tool provide any mechanisms to control auth for consumers of packages provided by satis?  The satis documentation mentions using an [API-Token in the repository configuration](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#security) to auth.  I'm curious if this gives us a way to manage that.

**Comment by tyler-sommer** [comment]
I know this is decades late, but:

Currently, no, the application only requires auth to manage the packages. The JSON files produced by Satis contain the remote URLs for each project-- the consumer still needs to have valid access.

At any rate, (very belated) thanks for checking out the project. Cheers!
