### ISSUE TITLE
Renaming a GitLab repository is not recognized by the Sync Task

### ISSUE THREAD

**Issue by strausmann** [terramar-labs/packages#44]
I renamed a GitLab repository and then clicked on the sync button. Unfortunately, the repository is still displayed with the old name and path.

**Comment by aschrammel** [comment]
Same problem here by moving an existing repository to a new namespace.

**Comment by tyler-sommer** [comment]
Thanks for the reports. This seems to be related to https://github.com/terramar-labs/packages/issues/26 as well.

**Comment by tyler-sommer** [comment]
Fixed in a8efd2df6b9daf88702d987bca5d17fc15bade07
