### ISSUE TITLE
Getting 500

### ISSUE THREAD

**Issue by nomadme** [terramar-labs/packages#45]
Just installed on fresh new server and followed the installation instruction and getting 500 error.

But /index_dev.php is working.

Any insight, how to get started on this packages?

**Comment by nomadme** [comment]
Got it working.

**Comment by CreativeBulma** [comment]
Hi @nomadme ,

I'm facing the same issue.
How did you fixed it ?

**Comment by nomadme** [comment]
@CreativeBulma 

Sorry, it's been a while. Can't remember it.
