### ISSUE TITLE
500 error with new sami

### ISSUE THREAD

**Issue by rebruCH** [terramar-labs/packages#48]
You should update your package, if it should be longer a solution for gitlab users ...

I did make a fresh install of the package, but the webhook didnt work anymore, if did a test on the gitlab it will show the following message in the log (and a 500 in the webhook site of gitlab)

`Uncaught exception 'Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException' with message 'No route found for "GET /webhook/24/receive": Method Not Allowed (Allow: POST)' in /cluster/var/www/site/packagist/vendor/nice/framework/src/Router/RouterSubscriber.php:63\nStack trace:\n#0 [internal function]: Nice\\Router\\RouterSubscriber->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#1 /cluster/var/www/site/packagist/vendor/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#2 /cluster/var/www/site/packagist/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEv in /cluster/var/www/site/packagist/vendor/nice/framework/src/Router/RouterSubscriber.php on line 63`

And btw ... sami with dev-master is a very bad idea, because they did update and force now php7 (little bit to earlier in my opinion, its not your fault)

Can you please have a look, because your tool is great, but if the webhook doesnt work, it is senseless, because the bin/console satis:update and satis:build didnt work too anymore.

**Comment by tyler-sommer** [comment]
Thanks for the bug report. I haven't had a chance to look into this issue yet, but it is on my radar. I'd love it if you could provide a pull request taking care of the issue, but no worries if not.

**Comment by tyler-sommer** [comment]
@rebruCH Which version of GitLab are you running? GitLab should be POSTing the webhook requests since they contain quite a large payload. Your stack trace implies otherwise, however.

PS. Thanks to the lovely @nickveenhof, the sami dependency is now pegged at ~1.4 👍

**Comment by tyler-sommer** [comment]
I'm going to close this ticket since the issue appears resolved. Please open a new issue if you run into any more problems!
