### ISSUE TITLE
Make packages.json and includes private

### ISSUE THREAD

**Issue by bernhardberger** [terramar-labs/packages#65]
Any ideas besides adding HTTP_BASIC_AUTH to hide the packages.json and it's respecitve includes from the public?

I'd like to have some Token/Auth based solution but no idea on how to solve this best..

**Comment by tyler-sommer** [comment]
It turns out HTTP Basic Auth is well supported by Composer, so I've done #68 -- take a look if you have some free time. I'd love to hear any suggestions you have.

**Comment by tyler-sommer** [comment]
Implemented in #68
