### ISSUE TITLE
No Metadata Classes to process.

### ISSUE THREAD

**Issue by jelovac** [terramar-labs/packages#70]
Hello,

I keep getting the following message when I run:  `bin/console orm:schema-tool:create`

> No Metadata Classes to process.

What am I doing wrong?

Steps to reproduce:
- clone the packages repository
- go inside the repository
- run composer install
- copy config.yml.dist to config.yml
- edit config.yml
- run `bin/console orm:schema-tool:create`

I even skipped editing of config.yml and tried to use default values and still the same error.

Best regards,
Vladimir

**Comment by tyler-sommer** [comment]
Hi Vladimir, thanks for opening an issue!

I followed the steps as you outlined and I'm able to run the `bin/console orm:schema-tool:create` command successfully.

Could you provide me with the version of PHP you're using? Could you also run `bin/console` with the `--verbose` flag enabled (so `bin/console orm:schema-tool:create --verbose`), then provide me the stack trace?

Thanks!

**Comment by tyler-sommer** [comment]
I'm closing this since it's been inactive for quite a while now. Please open a new issue if this error is still occurring. Thanks again!
