### ISSUE TITLE
Problem with composer update command

### ISSUE THREAD

**Issue by strausmann** [terramar-labs/packages#72]
Hello,

after execute the composer install command in to a fresh installation and the execute the command 

> composer update

i got this error message:

```
bash-4.1$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/satis dev-master requires php ^7.0 -> your PHP version (7.0.27) overridden by "config.platform.php" version (5.6) does not satisfy that requirement.
    - composer/satis dev-master requires php ^7.0 -> your PHP version (7.0.27) overridden by "config.platform.php" version (5.6) does not satisfy that requirement.
    - Installation request for composer/satis dev-master -> satisfiable by composer/satis[dev-master].
```

i try php 5.6 and 7.0 with the same result.

Regards,

Bjoern

**Comment by tyler-sommer** [comment]
Hi @strausmann !

In a normal installation, you should not need to run `composer update`. The dependencies defined in composer.lock are the dependencies 3.2.0 is designed to run with.

That being said, the underlying issue still exists. I've opened up #75 to solve the problem.

If you're still intent on running `composer update`, just change the `composer/satis` requirement in Packages's composer.json to `1.x-dev`.

I'm going to close this issue, but please open a new one if you have any further questions.

Thanks again!
