### ISSUE TITLE
Satis 2.x requires PHP 7+

### ISSUE THREAD

**Issue by tyler-sommer** [terramar-labs/packages#75]
Currently, Packages still supports PHP 5.6. Composer Satis (relatively) recently started work on 2.x line of Satis and are requiring PHP 7+.

We need to change the requirement in Packages' composer.json to use Satis's `1.x` branch:

```
    "composer/satis": "1.0-dev",
```

**Comment by blankse** [comment]
@tyler-sommer I created a PR for this: https://github.com/terramar-labs/packages/pull/108

**Comment by tyler-sommer** [comment]
There may still be issues around the monkey patches in lib, but we can deal with those as they come up.

Thanks for the PRs, @blankse !
