### ISSUE TITLE
500 error on sync remote in case remote repo was removed

### ISSUE THREAD

**Issue by NeoBlack** [terramar-labs/packages#86]
In case a repo was remoed on the remote, the sync of a remote fails with an 500 internal server error.

**Comment by NeoBlack** [comment]
looks like a duplication of #78

**Comment by tyler-sommer** [comment]
Thanks for the bug report! It does look like this is a duplicate of #78, so I'll close this issue. Please feel free to open a new issue :+1:

**Comment by NeoBlack** [comment]
no I am fine, I guess this is the same issue.
